#test:
#  mysql41: 9313
#  html_strip: 1
#  morphology: stem_en\
production:
  mysql41: 9312
  pid_file: ~/qna/shared/tmp/searchd.pid
  indices_location: ~/qna/shared/db/sphinx
  configuration_file: ~/qna/shared/production.sphinx.conf
  binlog_path: ~/qna/shared/binlog